window.RAMAN_GLOSSARY = [
  { key: 'accuracy', zh: '準確度', en: 'accuracy', aliasesZh: [], aliasesEn: [],
    defZh: '準確度描述量測值與真值的接近程度；重複量測很一致（精密度好）並不代表準確度好。',
    defEn: 'Accuracy describes how close a measurement is to the true value; consistent repeats (good precision) do not imply good accuracy.' },
  { key: 'acetaminophen', zh: '乙醯胺酚', en: 'acetaminophen', aliasesZh: ['普拿疼'], aliasesEn: ['paracetamol'],
    defZh: '乙醯胺酚是常見止痛藥的主成分，拉曼峰多且分布廣；教材用它比較校正前後的譜圖差異。',
    defEn: 'Acetaminophen is the main ingredient of a common painkiller and has many well-spread Raman peaks; the site uses it to compare spectra before and after calibration.' },
  { key: 'anti-stokes-line', zh: '反斯托克斯線', en: 'anti-Stokes line', aliasesZh: ['反史托克斯線'], aliasesEn: [],
    defZh: '反斯托克斯散射從分子獲得能量，故波長較雷射短；室溫下強度比斯托克斯側弱。',
    defEn: 'Anti-Stokes-scattered light gains energy from the molecule, so it has a shorter wavelength than the laser and is weaker at room temperature than the Stokes side.' },
  { key: 'aspartame', zh: '阿斯巴甜', en: 'aspartame', aliasesZh: [], aliasesEn: [],
    defZh: '阿斯巴甜是常見的代糖食品添加物；教材用它的拉曼指紋練習校正後的成分判讀。',
    defEn: 'Aspartame is a common sweetener food additive; the site uses its Raman fingerprint to practice identifying components after calibration.' },
  { key: 'astm-e1840', zh: 'ASTM E1840', en: 'ASTM E1840', aliasesZh: [], aliasesEn: [],
    defZh: 'ASTM E1840-96(2022)提供多種化合物的拉曼位移參考值；它不是完整的儀器校正程序。',
    defEn: 'ASTM E1840-96(2022) provides Raman-shift reference values for compounds; it is not a complete instrument calibration procedure.' },
  { key: 'background', zh: '背景', en: 'background', aliasesZh: ['背景訊號'], aliasesEn: [],
    defZh: '背景是與目標峰無關的訊號，可能來自暗電流、環境光或螢光；扣不扣背景會改變峰高與峰位的估計。',
    defEn: 'Background is signal unrelated to the target peak and may come from dark current, ambient light or fluorescence; whether it is subtracted changes estimated peak height and position.' },
  { key: 'baseline', zh: '基線', en: 'baseline', aliasesZh: [], aliasesEn: [],
    defZh: '基線是沒有目標峰時的背景訊號；先辨認它，才能正確估計峰高與峰位。',
    defEn: 'The baseline is background signal without a target peak; identifying it helps estimate peak height and position correctly.' },
  { key: 'benzoic-acid', zh: '苯甲酸', en: 'benzoic acid', aliasesZh: [], aliasesEn: [],
    defZh: '苯甲酸是教材用來反解雷射真實波長的食品添加物樣品，也用於拉曼光譜示範。',
    defEn: 'Benzoic acid is a food-additive sample used to infer the laser’s true wavelength and demonstrate Raman spectra.' },
  { key: 'caffeine', zh: '咖啡因', en: 'caffeine', aliasesZh: [], aliasesEn: [],
    defZh: '咖啡因是教材用來反解雷射真實波長的食品添加物樣品，也用於校正後的指紋比對。',
    defEn: 'Caffeine is a food-additive sample used to infer the laser’s true wavelength and compare calibrated fingerprints.' },
  { key: 'calibration-curve', zh: '校正曲線', en: 'calibration curve', aliasesZh: [], aliasesEn: [],
    defZh: '校正曲線把像素或波長等儀器座標轉成可信的波數；它由已知參考峰建立。',
    defEn: 'A calibration curve converts instrument coordinates such as pixels or wavelength into wavenumber, using known reference peaks.' },
  { key: 'ccd', zh: 'CCD', en: 'CCD', aliasesZh: [], aliasesEn: [],
    defZh: 'CCD（電荷耦合元件）把入射光轉成依像素排列的訊號；像素位置會影響波長對應。',
    defEn: 'A CCD converts incident light into signals arranged by pixel; pixel position affects the wavelength mapping.' },
  { key: 'cosmic-ray', zh: '宇宙射線', en: 'cosmic ray', aliasesZh: [], aliasesEn: ['cosmic ray spike'],
    defZh: '宇宙射線打到偵測器會產生只出現一次的尖銳假峰；比對重複量測就能認出並剔除。',
    defEn: 'A cosmic ray striking the detector creates a sharp false peak that appears in only one scan; comparing repeated scans identifies and removes it.' },
  { key: 'curve-fitting', zh: '擬合', en: 'curve fitting', aliasesZh: ['曲線擬合'], aliasesEn: ['fitting'],
    defZh: '擬合是用參數化的曲線去逼近資料點；模型太簡單會留下系統偏差，太複雜則會把雜訊也學進去。',
    defEn: 'Curve fitting approximates data points with a parameterized curve; too simple a model leaves systematic bias, while too complex a one also learns the noise.' },
  { key: 'dark-current', zh: '暗電流', en: 'dark current', aliasesZh: [], aliasesEn: [],
    defZh: '暗電流是無光時偵測器仍產生的像素訊號；不先扣除可能把假峰當成樣品訊號。',
    defEn: 'Dark current is pixel signal produced even without light; failing to remove it can create false sample peaks.' },
  { key: 'detector', zh: '偵測器', en: 'detector', aliasesZh: [], aliasesEn: [],
    defZh: '偵測器把光轉成可記錄的電訊號；其像素與雜訊會限制校正品質。',
    defEn: 'A detector converts light into recordable electrical signals; its pixels and noise limit calibration quality.' },
  { key: 'diffraction-grating', zh: '光柵', en: 'diffraction grating', aliasesZh: [], aliasesEn: [],
    defZh: '光柵以繞射與干涉把不同波長分開；其角度關係決定像素與波長的對應。',
    defEn: 'A diffraction grating separates wavelengths by diffraction and interference; its angular relation determines pixel-to-wavelength mapping.' },
  { key: 'dispersion', zh: '色散', en: 'dispersion', aliasesZh: [], aliasesEn: [],
    defZh: '色散描述波長改變時光譜位置改變的速率；色散錯誤會讓峰間距也跟著變形。',
    defEn: 'Dispersion describes how spectral position changes with wavelength; dispersion errors also distort distances between peaks.' },
  { key: 'doublet', zh: '雙線', en: 'doublet', aliasesZh: ['雙峰'], aliasesEn: [],
    defZh: '雙線是兩條靠得很近的譜線；解析度不足時會合成一個峰，此時質心不等於任一條線的真實位置。',
    defEn: 'A doublet is two closely spaced lines; when resolution is insufficient they merge into one peak, and the centroid is then not the true position of either line.' },
  { key: 'drift', zh: '漂移', en: 'drift', aliasesZh: ['熱漂移', '溫度漂移'], aliasesEn: ['thermal drift'],
    defZh: '漂移是儀器讀值隨時間或溫度緩慢變化；因此校正有時效，每個量測日都應重新確認。',
    defEn: 'Drift is a slow change in instrument readings with time or temperature; calibration therefore expires and should be re-checked on each measurement day.' },
  { key: 'emission-line', zh: '發射線', en: 'emission line', aliasesZh: [], aliasesEn: [],
    defZh: '發射線是原子或分子放出的窄譜線；已知波長的燈線可作波長軸參考。',
    defEn: 'An emission line is a narrow line emitted by atoms or molecules; known lamp wavelengths can reference the wavelength axis.' },
  { key: 'fluorescence', zh: '螢光', en: 'fluorescence', aliasesZh: [], aliasesEn: [],
    defZh: '螢光是樣品吸收光後產生的較寬背景，可能遮住拉曼峰並降低校正可靠度。',
    defEn: 'Fluorescence is broad background produced after a sample absorbs light; it can hide Raman peaks and reduce calibration reliability.' },
  { key: 'fluorescent-lamp', zh: '日光燈', en: 'fluorescent lamp', aliasesZh: [], aliasesEn: [],
    defZh: '日光燈含有可辨識的汞或氬發射線，可粗略檢查波長軸，但訊噪比通常較低。',
    defEn: 'A fluorescent lamp contains identifiable mercury or argon lines and can check the wavelength axis, but usually has lower signal-to-noise.' },
  { key: 'food-additive', zh: '食品添加物', en: 'food additive', aliasesZh: [], aliasesEn: [],
    defZh: '食品添加物是為改變或維持食品特性而加入的物質；教材用其拉曼指紋練習校正後判讀。',
    defEn: 'A food additive is added to change or maintain food properties; the site uses its Raman fingerprint to practice interpretation after calibration.' },
  { key: 'hg-ar-lamp', zh: '汞氬燈', en: 'Hg-Ar', aliasesZh: ['汞氬', '黑光燈', '汞氬黑光燈管'], aliasesEn: ['blacklight'],
    defZh: '汞氬燈的汞、氬發射線可作波長軸參考；黑光燈管通常比日光燈提供更強訊號。',
    defEn: 'Hg-Ar mercury and argon lines reference the wavelength axis; a blacklight tube usually provides stronger signals than a fluorescent lamp.' },
  { key: 'independent-validation', zh: '獨立驗證', en: 'independent validation', aliasesZh: [], aliasesEn: [],
    defZh: '獨立驗證用未參與建模的標準物檢查校正模型；教材以萘與聚苯乙烯驗證。',
    defEn: 'Independent validation checks a calibration model with standards not used for modeling; the site uses naphthalene and polystyrene.' },
  { key: 'integration-time', zh: '積分時間', en: 'integration time', aliasesZh: [], aliasesEn: [],
    defZh: '積分時間是偵測器累積光子的曝光時間；太短訊號弱，太長可能飽和。',
    defEn: 'Integration time is the detector exposure used to collect photons; too little weakens signal, while too much can saturate.' },
  { key: 'intensity-weighted-centroid', zh: '強度加權質心', en: 'intensity-weighted centroid', aliasesZh: ['一階矩'], aliasesEn: ['first moment'],
    defZh: '強度加權質心以扣背景後的淨強度為權重求波長平均，用來估計峰位；它需要孤立、近似對稱且背景處理良好的峰。',
    defEn: 'An intensity-weighted centroid averages wavelength with background-subtracted intensities as weights to estimate a peak position; it needs an isolated, roughly symmetric peak with a well-handled background.' },
  { key: 'intercept', zh: '截距', en: 'intercept', aliasesZh: [], aliasesEn: [],
    defZh: '截距是校正直線在 x = 0 時的 y 值；它對應整體平移，會讓所有峰一起往同一方向偏。',
    defEn: 'The intercept is the y value of a calibration line at x = 0; it corresponds to an overall offset that moves every peak in the same direction.' },
  { key: 'laser-power', zh: '雷射功率', en: 'laser power', aliasesZh: [], aliasesEn: [],
    defZh: '雷射功率影響訊號強度與樣品受熱；功率過高會燒壞樣品，也會讓矽等參考峰位移。',
    defEn: 'Laser power affects signal strength and sample heating; too much can burn the sample and also shifts reference peaks such as silicon.' },
  { key: 'laser-wavelength', zh: '雷射波長', en: 'laser wavelength', aliasesZh: [], aliasesEn: [],
    defZh: '雷射波長是入射雷射的實際波長；QEPro標稱785 nm，但實測約784.56–784.62 nm，會影響波數。',
    defEn: 'Laser wavelength is the actual incident wavelength; QEPro is nominally 785 nm but measures about 784.56–784.62 nm, affecting wavenumber.' },
  { key: 'least-squares', zh: '最小平方', en: 'least squares', aliasesZh: ['最小平方法'], aliasesEn: ['least-squares'],
    defZh: '最小平方法選出使殘差平方和最小的係數；線性迴歸與多項式迴歸都以它求解。',
    defEn: 'Least squares chooses the coefficients that minimize the sum of squared residuals; both linear and polynomial regression are solved this way.' },
  { key: 'linear-regression', zh: '線性迴歸', en: 'linear regression', aliasesZh: [], aliasesEn: [],
    defZh: '線性迴歸用直線描述兩變數關係；TREND以此作線性預測，最小平方是常用的擬合方法。',
    defEn: 'Linear regression fits a straight-line relationship; Excel TREND uses it for linear prediction, while least-squares fitting is the underlying fitting method.' },
  { key: 'median', zh: '中位數', en: 'median', aliasesZh: [], aliasesEn: [],
    defZh: '中位數是排序後位於中間的數值；它比平均值更不受少數異常點影響，適合估計粗略偏移。',
    defEn: 'The median is the middle value after sorting; it resists a few outliers better than the mean, which makes it suitable for estimating a rough offset.' },
  { key: 'naphthalene', zh: '萘', en: 'naphthalene', aliasesZh: [], aliasesEn: [],
    defZh: '萘是教材用於獨立驗證的ASTM參考材料，含多個可比對的拉曼峰。',
    defEn: 'Naphthalene is an ASTM reference material used for independent validation and has multiple Raman peaks for comparison.' },
  { key: 'near-infrared', zh: '近紅外', en: 'near-infrared', aliasesZh: [], aliasesEn: ['NIR'],
    defZh: '近紅外是接近可見光紅端的波段；燈線在此區可用來檢查波長軸。',
    defEn: 'Near-infrared is the band near the red end of visible light; lamp lines there can check the wavelength axis.' },
  { key: 'net-intensity', zh: '淨強度', en: 'net intensity', aliasesZh: [], aliasesEn: [],
    defZh: '淨強度是原始強度扣掉估計背景後的值；質心與峰面積都以它為權重，且總和必須大於 0。',
    defEn: 'Net intensity is the raw intensity minus the estimated background; centroids and peak areas use it as the weight, and its sum must be greater than 0.' },
  { key: 'nist', zh: 'NIST', en: 'NIST', aliasesZh: [], aliasesEn: [],
    defZh: 'NIST提供可追溯的原子譜線參考資料；教材用它比對日光燈或汞氬燈線。',
    defEn: 'NIST provides traceable atomic-line reference data; the site uses it to compare fluorescent-lamp or Hg-Ar lines.' },
  { key: 'noise', zh: '雜訊', en: 'noise', aliasesZh: [], aliasesEn: [],
    defZh: '雜訊是每次量測隨機起伏的部分；雜訊大時峰位會不穩定，可用平均或延長積分時間改善。',
    defEn: 'Noise is the randomly fluctuating part of a measurement; when it is large the peak position becomes unstable, which averaging or a longer integration time can improve.' },
  { key: 'nominal-value', zh: '標稱值', en: 'nominal value', aliasesZh: ['標稱'], aliasesEn: ['nominal'],
    defZh: '標稱值是規格書上寫的名目數值，例如「785 nm」；實際量測值可能與它差上零點幾奈米。',
    defEn: 'A nominal value is the figure quoted in the specification, such as "785 nm"; the measured value can differ from it by a few tenths of a nanometer.' },
  { key: 'offset', zh: '偏移', en: 'offset', aliasesZh: [], aliasesEn: [],
    defZh: '偏移是整條光譜相對真值的平移；雷射設定錯誤可能造成近似固定的波數偏移。',
    defEn: 'An offset is a translation of the whole spectrum from the true value; an incorrect laser setting can cause a nearly constant wavenumber offset.' },
  { key: 'optical-fiber', zh: '光纖', en: 'optical fiber', aliasesZh: [], aliasesEn: ['optical fibre'],
    defZh: '光纖把雷射導到探頭、再把散射光導回光譜儀；光纖材料本身也會產生背景訊號。',
    defEn: 'Optical fiber carries the laser to the probe and the scattered light back to the spectrometer; the fiber material itself also produces background signal.' },
  { key: 'peak', zh: '譜峰', en: 'peak', aliasesZh: ['拉曼峰', '校正峰', '參考峰', '鑽石峰'], aliasesEn: ['peaks'],
    defZh: '譜峰是光譜中的局部極值；校正時以已知參考峰位置建立座標關係。',
    defEn: 'A peak is a local extremum in a spectrum; calibration uses known reference-peak positions to establish coordinate relationships.' },
  { key: 'peak-position', zh: '峰位', en: 'peak position', aliasesZh: [], aliasesEn: [],
    defZh: '峰位是譜峰中心落在波長或波數軸上的位置；校正的目的就是讓它出現在正確的座標上。',
    defEn: 'Peak position is where a peak center falls on the wavelength or wavenumber axis; calibration exists to put it at the correct coordinate.' },
  { key: 'peak-wing', zh: '峰翼', en: 'peak wing', aliasesZh: [], aliasesEn: ['peak wings'],
    defZh: '峰翼是譜峰兩側逐漸下降的部分；取窗太窄會把峰翼切掉，使質心被拉向窗的中心。',
    defEn: 'The peak wings are the gradually decreasing sides of a peak; too narrow a window cuts them off and pulls the centroid toward the window center.' },
  { key: 'phosphor', zh: '磷光體', en: 'phosphor', aliasesZh: ['螢光粉'], aliasesEn: [],
    defZh: '磷光體是日光燈管內壁的塗層，會發出寬帶光；它疊在窄的汞氬線下方，干擾峰位判讀。',
    defEn: 'The phosphor is the coating inside a fluorescent tube and emits broad-band light; it sits under the narrow Hg-Ar lines and interferes with reading their positions.' },
  { key: 'pixel', zh: '像素', en: 'pixel', aliasesZh: [], aliasesEn: [],
    defZh: '像素是偵測器上的離散位置；原始資料中的峰先以像素表示，再換算成波長或波數。',
    defEn: 'A pixel is a discrete detector position; raw peaks are first represented by pixels, then converted to wavelength or wavenumber.' },
  { key: 'pixel-to-wavelength-mapping', zh: '像素轉波長', en: 'pixel-to-wavelength mapping', aliasesZh: ['像素 → 波長', 'pixel轉nm'], aliasesEn: [],
    defZh: '像素轉波長用已知參考線擬合多項式，把偵測器像素號換成波長值，建立波長軸。',
    defEn: 'Pixel-to-wavelength mapping converts detector pixel numbers into wavelength values, for example by fitting a polynomial to known reference lines; it constructs the wavelength axis.' },
  { key: 'polymorph', zh: '多晶型', en: 'polymorph', aliasesZh: [], aliasesEn: ['polymorphism'],
    defZh: '多晶型是同一化合物的不同結晶排列；它主要改變低波數的晶格振動，分子內振動大致不變。',
    defEn: 'Polymorphs are different crystal packings of the same compound; they mainly change low-wavenumber lattice modes while intramolecular vibrations stay nearly unchanged.' },
  { key: 'polynomial-regression', zh: '多項式迴歸', en: 'polynomial regression', aliasesZh: [], aliasesEn: [],
    defZh: '多項式迴歸用多項式描述像素與波數的關係；階數太高可能在參考範圍外失真。',
    defEn: 'Polynomial regression describes the pixel–wavenumber relationship with a polynomial; excessive degree can distort extrapolation.' },
  { key: 'polystyrene', zh: '聚苯乙烯', en: 'polystyrene', aliasesZh: [], aliasesEn: [],
    defZh: '聚苯乙烯是教材用於獨立驗證的ASTM參考材料，用其參考峰檢查校正。',
    defEn: 'Polystyrene is an ASTM reference material used for independent validation, with reference peaks that check calibration.' },
  { key: 'precision', zh: '精密度', en: 'precision', aliasesZh: [], aliasesEn: [],
    defZh: '精密度描述重複量測彼此的分散程度；它只反映隨機誤差，看不出系統誤差。',
    defEn: 'Precision describes the scatter among repeated measurements; it reflects random error only and cannot reveal systematic error.' },
  { key: 'raman-fingerprint', zh: '拉曼指紋', en: 'Raman fingerprint', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼指紋是樣品特有的峰組合，可用來比較或辨認物質；前提是波數軸已校正。',
    defEn: 'A Raman fingerprint is a sample-specific peak pattern for comparison or identification, provided the wavenumber axis is calibrated.' },
  { key: 'raman-scattering', zh: '拉曼散射', en: 'Raman scattering', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼散射是光子與分子或晶格振動交換能量後的非彈性散射。',
    defEn: 'Raman scattering is inelastic scattering in which photons exchange energy with molecular or lattice vibrations.' },
  { key: 'raman-shift', zh: '拉曼位移', en: 'Raman shift', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼位移是入射光與散射光的波數差，反映樣品的振動模式。',
    defEn: 'Raman shift is the wavenumber difference between incident and scattered light, reflecting sample vibrational modes.' },
  { key: 'random-error', zh: '隨機誤差', en: 'random error', aliasesZh: [], aliasesEn: [],
    defZh: '隨機誤差在重複量測間不可預測地變動，不同於系統性誤差；取重複值平均可降低它。',
    defEn: 'Random error varies unpredictably between repeated measurements, unlike systematic error, and averaging repeats can reduce it.' },
  { key: 'rayleigh-line', zh: '瑞利散射', en: 'Rayleigh scattering', aliasesZh: ['瑞利', '瑞利線'], aliasesEn: ['Rayleigh line', 'Rayleigh peak'],
    defZh: '瑞利散射是在雷射原本波長的彈性散射，拉曼位移為零；它遠強於拉曼散射，記錄拉曼訊號前會由陷波或邊緣濾光片移除。',
    defEn: 'Rayleigh scattering is elastic scattering at the laser’s own wavelength with zero Raman shift. It is much stronger than Raman scattering and is removed by a notch or edge filter before the Raman signal is recorded.' },
  { key: 'reference-standard', zh: '標準品', en: 'reference standard', aliasesZh: ['拉曼標準物'], aliasesEn: [],
    defZh: '標準品是具有已知參考峰值的材料；可用來建立或檢查波長、波數校正。',
    defEn: 'A reference standard has known reference-peak values and can establish or check wavelength and wavenumber calibration.' },
  { key: 'relative-intensity', zh: '相對強度', en: 'relative intensity', aliasesZh: [], aliasesEn: [],
    defZh: '相對強度是同一張譜中各峰高度的比例；它受儀器響應影響，不能直接當成濃度。',
    defEn: 'Relative intensity is the ratio of peak heights within one spectrum; it depends on instrument response and is not a direct measure of concentration.' },
  { key: 'repeatability', zh: '重複性', en: 'repeatability', aliasesZh: [], aliasesEn: [],
    defZh: '重複性描述同一條件下重複量測的一致程度；它反映精密度，不等於準確度。',
    defEn: 'Repeatability describes consistency under the same conditions; it reflects precision, not accuracy.' },
  { key: 'reproducibility', zh: '再現性', en: 'reproducibility', aliasesZh: [], aliasesEn: [],
    defZh: '再現性描述移開再放回或改變條件後結果的一致程度；它檢查方法是否穩定。',
    defEn: 'Reproducibility describes consistency after repositioning or changing conditions; it checks method stability.' },
  { key: 'residual', zh: '殘差', en: 'residual', aliasesZh: [], aliasesEn: [],
    defZh: '殘差是觀測值減模型預測值；檢查其大小與形狀可發現校正未處理的偏差。',
    defEn: 'A residual is an observation minus its model prediction; its size and shape reveal unhandled calibration bias.' },
  { key: 'rmse', zh: '均方根誤差', en: 'RMSE', aliasesZh: ['RMSE'], aliasesEn: [],
    defZh: '均方根誤差（RMSE）把多個殘差平方平均後開根號；數值越小代表整體偏差較小。',
    defEn: 'Root mean square error (RMSE) is the square root of mean squared residuals; smaller values indicate less overall deviation.' },
  { key: 'saturation', zh: '飽和', en: 'saturation', aliasesZh: ['訊號飽和'], aliasesEn: [],
    defZh: '飽和是像素訊號達到偵測器上限而被截平；峰頂被削掉後，峰高與峰位都不可信。',
    defEn: 'Saturation is a pixel reaching the detector ceiling and being clipped; once the top of a peak is cut off, neither its height nor its position is trustworthy.' },
  { key: 'second-order-diffraction', zh: '二階繞射', en: 'second-order diffraction', aliasesZh: [], aliasesEn: [],
    defZh: '二階繞射會讓波長λ的光在相同角度出現在約2λ，可能把短波線誤認成長波峰。',
    defEn: 'Second-order diffraction lets wavelength λ appear at the same angle near 2λ, so a short-wavelength line can mimic a long-wavelength peak.' },
  { key: 'signal-to-noise-ratio', zh: '訊噪比', en: 'signal-to-noise ratio', aliasesZh: ['訊噪'], aliasesEn: ['SNR'],
    defZh: '訊噪比比較目標訊號與雜訊大小；校正線訊噪比低時，峰位會不穩定。',
    defEn: 'Signal-to-noise ratio compares target signal with noise; low ratio in a calibration line makes peak position unstable.' },
  { key: 'silicon-wafer', zh: '矽晶圓', en: 'silicon wafer', aliasesZh: [], aliasesEn: ['silicon'],
    defZh: '矽晶圓的 520.7 cm⁻¹ 峰常用來每日快速檢查拉曼儀；此峰會隨雷射功率與溫度略為位移。',
    defEn: 'The 520.7 cm⁻¹ peak of a silicon wafer is often used for a quick daily Raman check; it shifts slightly with laser power and temperature.' },
  { key: 'slit', zh: '狹縫', en: 'slit', aliasesZh: ['入射狹縫'], aliasesEn: ['entrance slit'],
    defZh: '狹縫決定進入光譜儀的光束寬度；狹縫越寬訊號越強，但解析度變差、峰也變寬。',
    defEn: 'The slit sets the width of the beam entering the spectrometer; a wider slit gives more signal but poorer resolution and broader peaks.' },
  { key: 'slope', zh: '斜率', en: 'slope', aliasesZh: [], aliasesEn: [],
    defZh: '斜率是校正直線上 x 每增加一單位、y 改變的量；它對應色散，決定峰與峰的間距是否正確。',
    defEn: 'Slope is the change in y per unit of x along a calibration line; it corresponds to dispersion and decides whether the spacings between peaks are correct.' },
  { key: 'spectral-range', zh: '波長範圍', en: 'spectral range', aliasesZh: [], aliasesEn: [],
    defZh: '波長範圍是儀器可記錄的波長區間；參考線要涵蓋待校正的區域。',
    defEn: 'Spectral range is the wavelength interval an instrument records; reference lines should cover the region being calibrated.' },
  { key: 'spectral-resolution', zh: '解析度', en: 'spectral resolution', aliasesZh: [], aliasesEn: [],
    defZh: '解析度表示儀器分開相近譜線的能力；解析度不足會使峰重疊而難以定位。',
    defEn: 'Spectral resolution is the ability to separate nearby lines; insufficient resolution causes overlapping, hard-to-locate peaks.' },
  { key: 'spectrometer', zh: '光譜儀', en: 'spectrometer', aliasesZh: [], aliasesEn: ['spectrometers'],
    defZh: '光譜儀把光分光並記錄成光譜；校正是讓其座標能正確對應物理量。',
    defEn: 'A spectrometer separates and records light as a spectrum; calibration makes its coordinates correspond to physical quantities.' },
  { key: 'stokes-line', zh: '斯托克斯線', en: 'Stokes line', aliasesZh: ['史托克斯線', '斯托克斯散射', '史托克斯散射'], aliasesEn: ['Stokes scattering', 'Stokes lines'],
    defZh: '斯托克斯散射把能量傳給分子，故波長較雷射長、波數較低；拉曼常量測此側，頁面公式也以此為前提。',
    defEn: 'Stokes-scattered light loses energy to the molecule, so it has a longer wavelength and lower wavenumber than the laser. Raman spectra normally measure this side, assumed by the page formula.' },
  { key: 'systematic-error', zh: '系統誤差', en: 'systematic error', aliasesZh: ['系統性偏移'], aliasesEn: [],
    defZh: '系統性誤差會以一致方向或形狀出現在多次結果；只增加重複次數通常不能消除它。',
    defEn: 'Systematic error appears with a consistent direction or shape; more repeats alone usually cannot remove it.' },
  { key: 'traceability', zh: '可追溯', en: 'traceability', aliasesZh: ['追溯性', '溯源'], aliasesEn: ['traceable'],
    defZh: '可追溯是指量測結果能透過不間斷的比對鏈連回公認標準，例如 NIST 的譜線資料。',
    defEn: 'Traceability means a result can be linked back to a recognized standard, such as NIST line data, through an unbroken chain of comparisons.' },
  { key: 'uncertainty', zh: '不確定度', en: 'uncertainty', aliasesZh: [], aliasesEn: [],
    defZh: '不確定度量化量測結果合理可能的範圍；報告峰位或雷射波長時應一併給出，單一數字沒有它就不完整。',
    defEn: 'Uncertainty quantifies the range of values reasonably attributable to a measurement; report it together with a peak position or laser wavelength, because a single number alone is incomplete.' },
  { key: 'uv-vis', zh: 'UV-Vis', en: 'UV-Vis', aliasesZh: [], aliasesEn: [],
    defZh: 'UV-Vis是紫外–可見光分析的縮寫；教材以它標示可見光或近紅外量測通道。',
    defEn: 'UV-Vis abbreviates ultraviolet–visible analysis; the site uses it to label visible-light or near-infrared measurement channels.' },
  { key: 'wavelength', zh: '波長', en: 'wavelength', aliasesZh: [], aliasesEn: [],
    defZh: '波長是相鄰波峰間的距離；光譜儀先記錄它，再依雷射波長換算拉曼位移。',
    defEn: 'Wavelength is the distance between adjacent wave crests; the spectrometer records it before using laser wavelength to calculate Raman shift.' },
  { key: 'wavelength-axis', zh: '波長軸', en: 'wavelength axis', aliasesZh: [], aliasesEn: [],
    defZh: '波長軸是原始光譜圖以奈米（nm）表示的x軸；它由偵測器像素套用像素轉波長對應而成。',
    defEn: 'The wavelength axis is the raw-spectrum x-axis expressed in nanometers; it comes from applying pixel-to-wavelength mapping to detector pixel numbers.' },
  { key: 'wavelength-calibration', zh: '波長校正', en: 'wavelength calibration', aliasesZh: [], aliasesEn: [],
    defZh: '波長校正用已知發射線修正像素到波長的座標；它不同於直接校正拉曼位移。',
    defEn: 'Wavelength calibration corrects pixel-to-wavelength coordinates using known emission lines; it differs from direct Raman-shift calibration.' },
  { key: 'wavelength-to-wavenumber', zh: '波長轉波數', en: 'wavelength-to-wavenumber conversion', aliasesZh: [], aliasesEn: [],
    defZh: '波長轉波數用波長值與雷射波長的倒數公式算出拉曼位移，建立波數軸。',
    defEn: 'Wavelength-to-wavenumber conversion uses a wavelength value and the laser wavelength in a reciprocal formula to calculate Raman shift and construct the wavenumber axis.' },
  { key: 'wavenumber', zh: '波數', en: 'wavenumber', aliasesZh: [], aliasesEn: ['cm-1'],
    defZh: '波數是波長的倒數，拉曼光譜常用cm⁻¹表示；拉曼位移就是入射與散射波數的差。',
    defEn: 'Wavenumber is the reciprocal of wavelength and is commonly expressed in cm⁻¹; Raman shift is the incident–scattered wavenumber difference.' },
  { key: 'wavenumber-axis', zh: '波數軸', en: 'wavenumber axis', aliasesZh: [], aliasesEn: [],
    defZh: '波數軸是以波數（拉曼位移）表示的x軸，用含雷射波長的轉換由波長軸建立，用來辨認與比較拉曼峰。',
    defEn: 'The wavenumber axis is the x-axis in wavenumber (Raman shift), built from the wavelength axis using the laser wavelength to identify and compare Raman peaks.' }
];
