window.RAMAN_GLOSSARY = [
  { key: 'anti-stokes-line', zh: '反斯托克斯線', en: 'anti-Stokes line', aliasesZh: ['反史托克斯線'], aliasesEn: [],
    defZh: '反斯托克斯散射從分子獲得能量，故波長較雷射短；室溫下強度比斯托克斯側弱。',
    defEn: 'Anti-Stokes-scattered light gains energy from the molecule, so it has a shorter wavelength than the laser and is weaker at room temperature than the Stokes side.' },
  { key: 'astm-e1840', zh: 'ASTM E1840', en: 'ASTM E1840', aliasesZh: [], aliasesEn: [],
    defZh: 'ASTM E1840-96(2022)提供多種化合物的拉曼位移參考值；它不是完整的儀器校正程序。',
    defEn: 'ASTM E1840-96(2022) provides Raman-shift reference values for compounds; it is not a complete instrument calibration procedure.' },
  { key: 'baseline', zh: '基線', en: 'baseline', aliasesZh: [], aliasesEn: [],
    defZh: '基線是沒有目標峰時的背景訊號；先辨認它，才能正確估計峰高與峰位。',
    defEn: 'The baseline is background signal without a target peak; identifying it helps estimate peak height and position correctly.' },
  { key: 'benzoic-acid', zh: '苯甲酸', en: 'benzoic acid', aliasesZh: [], aliasesEn: [],
    defZh: '苯甲酸是教材用來反解雷射真實波長的食品添加物樣品，也用於拉曼光譜示範。',
    defEn: 'Benzoic acid is a food-additive sample used to infer the laser’s true wavelength and demonstrate Raman spectra.' },
  { key: 'caffeine', zh: '咖啡因', en: 'caffeine', aliasesZh: [], aliasesEn: [],
    defZh: '咖啡因是教材用來反解雷射真實波長的食品添加物樣品，也用於校正後的指紋比對。',
    defEn: 'Caffeine is a food-additive sample used to infer the laser’s true wavelength and compare calibrated fingerprints.' },
  { key: 'calibration-curve', zh: '校正曲線', en: 'calibration curve', aliasesZh: [], aliasesEn: [],
    defZh: '校正曲線把像素或波長等儀器座標轉成可信的波數；它由已知參考峰建立。',
    defEn: 'A calibration curve converts instrument coordinates such as pixels or wavelength into wavenumber, using known reference peaks.' },
  { key: 'ccd', zh: 'CCD', en: 'CCD', aliasesZh: [], aliasesEn: [],
    defZh: 'CCD（電荷耦合元件）把入射光轉成依像素排列的訊號；像素位置會影響波長對應。',
    defEn: 'A CCD converts incident light into signals arranged by pixel; pixel position affects the wavelength mapping.' },
  { key: 'dark-current', zh: '暗電流', en: 'dark current', aliasesZh: [], aliasesEn: [],
    defZh: '暗電流是無光時偵測器仍產生的像素訊號；不先扣除可能把假峰當成樣品訊號。',
    defEn: 'Dark current is pixel signal produced even without light; failing to remove it can create false sample peaks.' },
  { key: 'detector', zh: '偵測器', en: 'detector', aliasesZh: [], aliasesEn: [],
    defZh: '偵測器把光轉成可記錄的電訊號；其像素與雜訊會限制校正品質。',
    defEn: 'A detector converts light into recordable electrical signals; its pixels and noise limit calibration quality.' },
  { key: 'diffraction-grating', zh: '光柵', en: 'diffraction grating', aliasesZh: [], aliasesEn: [],
    defZh: '光柵以繞射與干涉把不同波長分開；其角度關係決定像素與波長的對應。',
    defEn: 'A diffraction grating separates wavelengths by diffraction and interference; its angular relation determines pixel-to-wavelength mapping.' },
  { key: 'dispersion', zh: '色散', en: 'dispersion', aliasesZh: [], aliasesEn: [],
    defZh: '色散描述波長改變時光譜位置改變的速率；色散錯誤會讓峰間距也跟著變形。',
    defEn: 'Dispersion describes how spectral position changes with wavelength; dispersion errors also distort distances between peaks.' },
  { key: 'emission-line', zh: '發射線', en: 'emission line', aliasesZh: [], aliasesEn: [],
    defZh: '發射線是原子或分子放出的窄譜線；已知波長的燈線可作波長軸參考。',
    defEn: 'An emission line is a narrow line emitted by atoms or molecules; known lamp wavelengths can reference the wavelength axis.' },
  { key: 'fluorescence', zh: '螢光', en: 'fluorescence', aliasesZh: [], aliasesEn: [],
    defZh: '螢光是樣品吸收光後產生的較寬背景，可能遮住拉曼峰並降低校正可靠度。',
    defEn: 'Fluorescence is broad background produced after a sample absorbs light; it can hide Raman peaks and reduce calibration reliability.' },
  { key: 'fluorescent-lamp', zh: '日光燈', en: 'fluorescent lamp', aliasesZh: [], aliasesEn: [],
    defZh: '日光燈含有可辨識的汞或氬發射線，可粗略檢查波長軸，但訊噪比通常較低。',
    defEn: 'A fluorescent lamp contains identifiable mercury or argon lines and can check the wavelength axis, but usually has lower signal-to-noise.' },
  { key: 'food-additive', zh: '食品添加物', en: 'food additive', aliasesZh: [], aliasesEn: [],
    defZh: '食品添加物是為改變或維持食品特性而加入的物質；教材用其拉曼指紋練習校正後判讀。',
    defEn: 'A food additive is added to change or maintain food properties; the site uses its Raman fingerprint to practice interpretation after calibration.' },
  { key: 'hg-ar-lamp', zh: '汞氬燈', en: 'Hg-Ar', aliasesZh: ['汞氬', '黑光燈', '汞氬黑光燈管'], aliasesEn: ['blacklight'],
    defZh: '汞氬燈的汞、氬發射線可作波長軸參考；黑光燈管通常比日光燈提供更強訊號。',
    defEn: 'Hg-Ar mercury and argon lines reference the wavelength axis; a blacklight tube usually provides stronger signals than a fluorescent lamp.' },
  { key: 'independent-validation', zh: '獨立驗證', en: 'independent validation', aliasesZh: [], aliasesEn: [],
    defZh: '獨立驗證用未參與建模的標準物檢查校正模型；教材以萘與聚苯乙烯驗證。',
    defEn: 'Independent validation checks a calibration model with standards not used for modeling; the site uses naphthalene and polystyrene.' },
  { key: 'integration-time', zh: '積分時間', en: 'integration time', aliasesZh: [], aliasesEn: [],
    defZh: '積分時間是偵測器累積光子的曝光時間；太短訊號弱，太長可能飽和。',
    defEn: 'Integration time is the detector exposure used to collect photons; too little weakens signal, while too much can saturate.' },
  { key: 'laser-wavelength', zh: '雷射波長', en: 'laser wavelength', aliasesZh: [], aliasesEn: [],
    defZh: '雷射波長是入射雷射的實際波長；QEPro標稱785 nm，但實測約784.56–784.62 nm，會影響波數。',
    defEn: 'Laser wavelength is the actual incident wavelength; QEPro is nominally 785 nm but measures about 784.56–784.62 nm, affecting wavenumber.' },
  { key: 'linear-regression', zh: '線性迴歸', en: 'linear regression', aliasesZh: [], aliasesEn: [],
    defZh: '線性迴歸用直線描述兩變數關係；TREND以此作線性預測，最小平方是常用的擬合方法。',
    defEn: 'Linear regression fits a straight-line relationship; Excel TREND uses it for linear prediction, while least-squares fitting is the underlying fitting method.' },
  { key: 'naphthalene', zh: '萘', en: 'naphthalene', aliasesZh: [], aliasesEn: [],
    defZh: '萘是教材用於獨立驗證的ASTM參考材料，含多個可比對的拉曼峰。',
    defEn: 'Naphthalene is an ASTM reference material used for independent validation and has multiple Raman peaks for comparison.' },
  { key: 'near-infrared', zh: '近紅外', en: 'near-infrared', aliasesZh: [], aliasesEn: ['NIR'],
    defZh: '近紅外是接近可見光紅端的波段；燈線在此區可用來檢查波長軸。',
    defEn: 'Near-infrared is the band near the red end of visible light; lamp lines there can check the wavelength axis.' },
  { key: 'nist', zh: 'NIST', en: 'NIST', aliasesZh: [], aliasesEn: [],
    defZh: 'NIST提供可追溯的原子譜線參考資料；教材用它比對日光燈或汞氬燈線。',
    defEn: 'NIST provides traceable atomic-line reference data; the site uses it to compare fluorescent-lamp or Hg-Ar lines.' },
  { key: 'offset', zh: '偏移', en: 'offset', aliasesZh: [], aliasesEn: [],
    defZh: '偏移是整條光譜相對真值的平移；雷射設定錯誤可能造成近似固定的波數偏移。',
    defEn: 'An offset is a translation of the whole spectrum from the true value; an incorrect laser setting can cause a nearly constant wavenumber offset.' },
  { key: 'peak', zh: '譜峰', en: 'peak', aliasesZh: ['拉曼峰', '校正峰', '參考峰', '鑽石峰'], aliasesEn: ['peaks'],
    defZh: '譜峰是光譜中的局部極值；校正時以已知參考峰位置建立座標關係。',
    defEn: 'A peak is a local extremum in a spectrum; calibration uses known reference-peak positions to establish coordinate relationships.' },
  { key: 'pixel', zh: '像素', en: 'pixel', aliasesZh: [], aliasesEn: [],
    defZh: '像素是偵測器上的離散位置；原始資料中的峰先以像素表示，再換算成波長或波數。',
    defEn: 'A pixel is a discrete detector position; raw peaks are first represented by pixels, then converted to wavelength or wavenumber.' },
  { key: 'pixel-to-wavelength-mapping', zh: '像素轉波長', en: 'pixel-to-wavelength mapping', aliasesZh: ['像素 → 波長', 'pixel轉nm'], aliasesEn: [],
    defZh: '像素轉波長用已知參考線擬合多項式，把偵測器像素號換成波長值，建立波長軸。',
    defEn: 'Pixel-to-wavelength mapping converts detector pixel numbers into wavelength values, for example by fitting a polynomial to known reference lines; it constructs the wavelength axis.' },
  { key: 'polynomial-regression', zh: '多項式迴歸', en: 'polynomial regression', aliasesZh: [], aliasesEn: [],
    defZh: '多項式迴歸用多項式描述像素與波數的關係；階數太高可能在參考範圍外失真。',
    defEn: 'Polynomial regression describes the pixel–wavenumber relationship with a polynomial; excessive degree can distort extrapolation.' },
  { key: 'polystyrene', zh: '聚苯乙烯', en: 'polystyrene', aliasesZh: [], aliasesEn: [],
    defZh: '聚苯乙烯是教材用於獨立驗證的ASTM參考材料，用其參考峰檢查校正。',
    defEn: 'Polystyrene is an ASTM reference material used for independent validation, with reference peaks that check calibration.' },
  { key: 'raman-fingerprint', zh: '拉曼指紋', en: 'Raman fingerprint', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼指紋是樣品特有的峰組合，可用來比較或辨認物質；前提是波數軸已校正。',
    defEn: 'A Raman fingerprint is a sample-specific peak pattern for comparison or identification, provided the wavenumber axis is calibrated.' },
  { key: 'raman-scattering', zh: '拉曼散射', en: 'Raman scattering', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼散射是光子與分子或晶格振動交換能量後的非彈性散射。',
    defEn: 'Raman scattering is inelastic scattering in which photons exchange energy with molecular or lattice vibrations.' },
  { key: 'raman-shift', zh: '拉曼位移', en: 'Raman shift', aliasesZh: [], aliasesEn: [],
    defZh: '拉曼位移是入射光與散射光的波數差，反映樣品的振動模式。',
    defEn: 'Raman shift is the wavenumber difference between incident and scattered light, reflecting sample vibrational modes.' },
  { key: 'random-error', zh: '隨機誤差', en: 'random error', aliasesZh: [], aliasesEn: [],
    defZh: '隨機誤差在重複量測間不可預測地變動，不同於系統性誤差；取重複值平均可降低它。',
    defEn: 'Random error varies unpredictably between repeated measurements, unlike systematic error, and averaging repeats can reduce it.' },
  { key: 'rayleigh-line', zh: '瑞利散射', en: 'Rayleigh scattering', aliasesZh: ['瑞利', '瑞利線'], aliasesEn: ['Rayleigh line', 'Rayleigh peak'],
    defZh: '瑞利散射是在雷射原本波長的彈性散射，拉曼位移為零；它遠強於拉曼散射，記錄拉曼訊號前會由陷波或邊緣濾光片移除。',
    defEn: 'Rayleigh scattering is elastic scattering at the laser’s own wavelength with zero Raman shift. It is much stronger than Raman scattering and is removed by a notch or edge filter before the Raman signal is recorded.' },
  { key: 'reference-standard', zh: '標準品', en: 'reference standard', aliasesZh: ['拉曼標準物'], aliasesEn: [],
    defZh: '標準品是具有已知參考峰值的材料；可用來建立或檢查波長、波數校正。',
    defEn: 'A reference standard has known reference-peak values and can establish or check wavelength and wavenumber calibration.' },
  { key: 'repeatability', zh: '重複性', en: 'repeatability', aliasesZh: [], aliasesEn: [],
    defZh: '重複性描述同一條件下重複量測的一致程度；它反映精密度，不等於準確度。',
    defEn: 'Repeatability describes consistency under the same conditions; it reflects precision, not accuracy.' },
  { key: 'reproducibility', zh: '再現性', en: 'reproducibility', aliasesZh: [], aliasesEn: [],
    defZh: '再現性描述移開再放回或改變條件後結果的一致程度；它檢查方法是否穩定。',
    defEn: 'Reproducibility describes consistency after repositioning or changing conditions; it checks method stability.' },
  { key: 'residual', zh: '殘差', en: 'residual', aliasesZh: [], aliasesEn: [],
    defZh: '殘差是觀測值減模型預測值；檢查其大小與形狀可發現校正未處理的偏差。',
    defEn: 'A residual is an observation minus its model prediction; its size and shape reveal unhandled calibration bias.' },
  { key: 'rmse', zh: '均方根誤差', en: 'RMSE', aliasesZh: ['RMSE'], aliasesEn: [],
    defZh: '均方根誤差（RMSE）把多個殘差平方平均後開根號；數值越小代表整體偏差較小。',
    defEn: 'Root mean square error (RMSE) is the square root of mean squared residuals; smaller values indicate less overall deviation.' },
  { key: 'second-order-diffraction', zh: '二階繞射', en: 'second-order diffraction', aliasesZh: [], aliasesEn: [],
    defZh: '二階繞射會讓波長λ的光在相同角度出現在約2λ，可能把短波線誤認成長波峰。',
    defEn: 'Second-order diffraction lets wavelength λ appear at the same angle near 2λ, so a short-wavelength line can mimic a long-wavelength peak.' },
  { key: 'signal-to-noise-ratio', zh: '訊噪比', en: 'signal-to-noise ratio', aliasesZh: ['訊噪'], aliasesEn: ['SNR'],
    defZh: '訊噪比比較目標訊號與雜訊大小；校正線訊噪比低時，峰位會不穩定。',
    defEn: 'Signal-to-noise ratio compares target signal with noise; low ratio in a calibration line makes peak position unstable.' },
  { key: 'spectral-range', zh: '波長範圍', en: 'spectral range', aliasesZh: [], aliasesEn: [],
    defZh: '波長範圍是儀器可記錄的波長區間；參考線要涵蓋待校正的區域。',
    defEn: 'Spectral range is the wavelength interval an instrument records; reference lines should cover the region being calibrated.' },
  { key: 'spectral-resolution', zh: '解析度', en: 'spectral resolution', aliasesZh: [], aliasesEn: [],
    defZh: '解析度表示儀器分開相近譜線的能力；解析度不足會使峰重疊而難以定位。',
    defEn: 'Spectral resolution is the ability to separate nearby lines; insufficient resolution causes overlapping, hard-to-locate peaks.' },
  { key: 'spectrometer', zh: '光譜儀', en: 'spectrometer', aliasesZh: [], aliasesEn: ['spectrometers'],
    defZh: '光譜儀把光分光並記錄成光譜；校正是讓其座標能正確對應物理量。',
    defEn: 'A spectrometer separates and records light as a spectrum; calibration makes its coordinates correspond to physical quantities.' },
  { key: 'stokes-line', zh: '斯托克斯線', en: 'Stokes line', aliasesZh: ['史托克斯線', '斯托克斯散射', '史托克斯散射'], aliasesEn: ['Stokes scattering', 'Stokes lines'],
    defZh: '斯托克斯散射把能量傳給分子，故波長較雷射長、波數較低；拉曼常量測此側，頁面公式也以此為前提。',
    defEn: 'Stokes-scattered light loses energy to the molecule, so it has a longer wavelength and lower wavenumber than the laser. Raman spectra normally measure this side, assumed by the page formula.' },
  { key: 'systematic-error', zh: '系統誤差', en: 'systematic error', aliasesZh: ['系統性偏移'], aliasesEn: [],
    defZh: '系統性誤差會以一致方向或形狀出現在多次結果；只增加重複次數通常不能消除它。',
    defEn: 'Systematic error appears with a consistent direction or shape; more repeats alone usually cannot remove it.' },
  { key: 'uv-vis', zh: 'UV-Vis', en: 'UV-Vis', aliasesZh: [], aliasesEn: [],
    defZh: 'UV-Vis是紫外–可見光分析的縮寫；教材以它標示可見光或近紅外量測通道。',
    defEn: 'UV-Vis abbreviates ultraviolet–visible analysis; the site uses it to label visible-light or near-infrared measurement channels.' },
  { key: 'wavelength', zh: '波長', en: 'wavelength', aliasesZh: [], aliasesEn: [],
    defZh: '波長是相鄰波峰間的距離；光譜儀先記錄它，再依雷射波長換算拉曼位移。',
    defEn: 'Wavelength is the distance between adjacent wave crests; the spectrometer records it before using laser wavelength to calculate Raman shift.' },
  { key: 'wavelength-axis', zh: '波長軸', en: 'wavelength axis', aliasesZh: [], aliasesEn: [],
    defZh: '波長軸是原始光譜圖以奈米（nm）表示的x軸；它由偵測器像素套用像素轉波長對應而成。',
    defEn: 'The wavelength axis is the raw-spectrum x-axis expressed in nanometers; it comes from applying pixel-to-wavelength mapping to detector pixel numbers.' },
  { key: 'wavelength-calibration', zh: '波長校正', en: 'wavelength calibration', aliasesZh: [], aliasesEn: [],
    defZh: '波長校正用已知發射線修正像素到波長的座標；它不同於直接校正拉曼位移。',
    defEn: 'Wavelength calibration corrects pixel-to-wavelength coordinates using known emission lines; it differs from direct Raman-shift calibration.' },
  { key: 'wavelength-to-wavenumber', zh: '波長轉波數', en: 'wavelength-to-wavenumber conversion', aliasesZh: [], aliasesEn: [],
    defZh: '波長轉波數用波長值與雷射波長的倒數公式算出拉曼位移，建立波數軸。',
    defEn: 'Wavelength-to-wavenumber conversion uses a wavelength value and the laser wavelength in a reciprocal formula to calculate Raman shift and construct the wavenumber axis.' },
  { key: 'wavenumber', zh: '波數', en: 'wavenumber', aliasesZh: [], aliasesEn: ['cm-1'],
    defZh: '波數是波長的倒數，拉曼光譜常用cm⁻¹表示；拉曼位移就是入射與散射波數的差。',
    defEn: 'Wavenumber is the reciprocal of wavelength and is commonly expressed in cm⁻¹; Raman shift is the incident–scattered wavenumber difference.' },
  { key: 'wavenumber-axis', zh: '波數軸', en: 'wavenumber axis', aliasesZh: [], aliasesEn: [],
    defZh: '波數軸是以波數（拉曼位移）表示的x軸，用含雷射波長的轉換由波長軸建立，用來辨認與比較拉曼峰。',
    defEn: 'The wavenumber axis is the x-axis in wavenumber (Raman shift), built from the wavelength axis using the laser wavelength to identify and compare Raman peaks.' }
];
